apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nguyenchithanh/loopme-auth-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: loopme-config
                  key: MONGO_URI
            - name: APP_PORT
              value: "8001"
            - name: APP_HOST
              value: "0.0.0.0"
            - name: BUILD_MODE
              valueFrom:
                configMapKeyRef:
                  name: loopme-config
                  key: BUILD_MODE
            - name: AMQP_PORT
              valueFrom:
                configMapKeyRef:
                  name: loopme-config
                  key: AMQP_PORT
            - name: JWT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: loopme-secrets
                  key: JWT_ACCESS_TOKEN
            - name: JWT_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: loopme-secrets
                  key: JWT_REFRESH_TOKEN
