apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: your-docker-repo/auth-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/loopme"
            - name: APP_PORT
              value: "8001"
