apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: nguyenchithanh/loopme-post-service:latest
          ports:
            - containerPort: 8007
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: loopme-config
                  key: MONGO_URI
            - name: APP_PORT
              value: "8007"
            - name: APP_HOST
              value: "0.0.0.0"
            - name: BUILD_MODE
              valueFrom:
                configMapKeyRef:
                  name: loopme-config
                  key: BUILD_MODE
            - name: AMQP_PORT
              valueFrom:
                configMapKeyRef:
                  name: loopme-config
                  key: AMQP_PORT
