apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-service
  template:
    metadata:
      labels:
        app: realtime-service
    spec:
      containers:
        - name: realtime-service
          image: nguyenchithanh/loopme-realtime-service:latest
          ports:
            - containerPort: 8009
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: loopme-config
                  key: MONGO_URI
            - name: APP_PORT
              value: "8009"
            - name: APP_HOST
              value: "0.0.0.0"
            - name: BUILD_MODE
              valueFrom:
                configMapKeyRef:
                  name: loopme-config
                  key: BUILD_MODE
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: loopme-config
                  key: REDIS_URL
